# SPDX-FileCopyrightText: 2025 Sector-Vestige contributors
# SPDX-FileCopyrightText: 2025 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2025 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Custom department for high-level Central Command roles that are player-selectable
- type: department
  id: SVCentralCommand
  name: department-sv-centralcommand
  description: department-sv-centralcommand-description
  color: "#0c344d"
  roles:
  - SVMagistrate
  weight: 115
