version = 1
SPDX-PackageName = "Sector-Vestige"
SPDX-PackageDownloadLocation = "https://github.com/Sector-Vestige/Sector-Vestige"

[[annotations]]
path = "Content.Server/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Content.Client/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Content.Shared/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Content.Docfx/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Tools/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Content.Server/_LateStation/**", "Content.Client/_LateStation/**", "Content.Shared/_LateStation/**", "Resources/_LateStation/**", "Resources/Prototypes/_LateStation/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2025 LateStation14 contributors"
SPDX-License-Identifier = "MIT OR AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_AXOLOTL/**", "Content.Client/_AXOLOTL/**", "Content.Shared/_AXOLOTL/**", "Resources/_AXOLOTL/**", "Resources/Prototypes/_AXOLOTL/**", "Resources/Audio/_AXOLOTL/**", "Resources/Textures/_AXOLOTL/**", "Resources/Locale/_AXOLOTL/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 AXOLOTL contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Content.Server/_CD/**", "Content.Client/_CD/**", "Content.Shared/_CD/**", "Resources/_CD/**", "Resources/Prototypes/_CD/**", "Resources/Audio/_CD/**", "Resources/Textures/_CD/**", "Resources/Locale/_CD/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Cosmatic Drift contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Content.Server/_DV/**", "Content.Client/_DV/**", "Content.Shared/_DV/**", "Resources/_DV/**", "Resources/Prototypes/_DV/**", "Resources/Audio/_DV/**", "Resources/Textures/_DV/**", "Resources/Locale/_DV/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Delta-V contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_NF/**", "Content.Client/_NF/**", "Content.Shared/_NF/**", "Resources/_NF/**", "Resources/Prototypes/_NF/**", "Resources/Audio/_NF/**", "Resources/Textures/_NF/**", "Resources/Locale/_NF/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 New Frontiers contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_Harmony/**", "Content.Client/_Harmony/**", "Content.Shared/_Harmony/**", "Resources/_Harmony/**", "Resources/Prototypes/_Harmony/**", "Resources/Audio/_Harmony/**", "Resources/Textures/_Harmony/**", "Resources/Locale/_Harmony/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Harmony contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_Umbra/**", "Content.Client/_Umbra/**", "Content.Shared/_Umbra/**", "Resources/_Umbra/**", "Resources/Prototypes/_Umbra/**", "Resources/Audio/_Umbra/**", "Resources/Textures/_Umbra/**", "Resources/Locale/_Umbra/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Umbra contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Content.Server/_Floofstation/**", "Content.Client/_Floofstation/**", "Content.Shared/_Floofstation/**", "Resources/_Floofstation/**", "Resources/Prototypes/_Floofstation/**", "Resources/Audio/_Floofstation/**", "Resources/Textures/_Floofstation/**", "Resources/Locale/_Floofstation/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 FloofStation contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_Impstation/**", "Content.Client/_Impstation/**", "Content.Shared/_Impstation/**", "Resources/_Impstation/**", "Resources/Prototypes/_Impstation/**", "Resources/Audio/_Impstation/**", "Resources/Textures/_Impstation/**", "Resources/Locale/_Impstation/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Impstation contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_EE/**", "Content.Client/_EE/**", "Content.Shared/_EE/**", "Resources/_EE/**", "Resources/Prototypes/_EE/**", "Resources/Audio/_EE/**", "Resources/Textures/_EE/**", "Resources/Locale/_EE/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 EinsteinEngines contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_Funkystation/**", "Content.Client/_Funkystation/**", "Content.Shared/_Funkystation/**", "Resources/_Funkystation/**", "Resources/Prototypes/_Funkystation/**", "Resources/Audio/_Funkystation/**", "Resources/Textures/_Funkystation/**", "Resources/Locale/_Funkystation/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Funkystation contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_SV/**", "Content.Client/_SV/**", "Content.Shared/_SV/**", "Resources/_SV/**", "Resources/Prototypes/_SV/**", "Resources/Audio/_SV/**", "Resources/Textures/_SV/**", "Resources/Locale/_SV/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Sector-Vestige contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["Content.Server/_Moffstation/**", "Content.Client/_Moffstation/**", "Content.Shared/_Moffstation/**", "Resources/_Moffstation/**", "Resources/Prototypes/_Moffstation/**", "Resources/Audio/_Moffstation/**", "Resources/Textures/_Moffstation/**", "Resources/Locale/_Moffstation/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Moffstation contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Content.Server/_Goobstation/**", "Content.Client/_Goobstation/**", "Content.Shared/_Goobstation/**", "Resources/_Goobstation/**", "Resources/Prototypes/_Goobstation/**", "Resources/Audio/_Goobstation/**", "Resources/Textures/_Goobstation/**", "Resources/Locale/_Goobstation/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Goob-Station contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "Resources/Textures/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["SS14 contributors (Check meta files)", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = "Resources/Locale/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Resources/Prototypes/**", "Resources/ServerInfo/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Changelog/**", "Resources/ConfigPresets/**", "Resources/Credits/**", "Resources/Fonts/**", "Resources/IgnoredPrototypes/**", "Resources/Maps/**", "Resources/**.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.md", "**.txt", "**.nix", "**.lock", "**.toml", "**.sln**", "**.bat", "**.sh", "**.py", "**.props", "**.csproj.DotSettings", "**.json", ".editorconfig", ".envrc", ".gitattributes", ".gitignore", ".gitmodules", "bors.toml", "nuget.config", "global.json", "omnisharp.json", "README.md", "LICENSE.TXT", "LICENSE-AGPLv3.txt", "SpaceStation14.sln"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".run/**", "BuildChecker/**", "BuildFiles/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["Content.Benchmarks/**", "Content.IntegrationTests/**", "Content.MapRenderer/**", "Content.Packaging/**", "Content.PatreonParser/**", "Content.Replay/**", "Content.Server.Database/**", "Content.Shared.Database/**", "Content.Tests/**", "Content.Tools/**", "Content.YAMLLinter/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Pow3r/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020-2025 Wizards Den contributors", "2020-2025 Sector Vestige contributors (modifications)"]
SPDX-License-Identifier = "MIT"
