# SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagCategory
  id: Independent
  name: antag-category-independent

- type: antagCategory
  id: Syndicate
  name: antag-category-syndicate

- type: antagCategory
  id: NanoTrasen
  name: antag-category-nanotrasen

- type: antagCategory
  id: OptIn
  name: antag-category-optin
