# SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# NANOTRASEN ALIGNED ROLES

- type: antag
  id: NanoTrasenAgent
  name: roles-nanotrasen-agent
  antagonist: true
  setPreference: true
  objective: roles-nanotrasen-agent-desc
  visiblePreference: true
  category: NanoTrasen

- type: antag
  id: NanoTrasenOperative
  name: roles-nanotrasen-operative
  antagonist: true
  setPreference: true
  objective: roles-nanotrasen-operative-desc
  visiblePreference: true
  category: NanoTrasen
