# SPDX-FileCopyrightText: 2025 Cosmatic Drift contributors
# SPDX-FileCopyrightText: 2025 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2025 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: MIT

- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  setPreference: true
  whitelisted: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled

- type: chameleonOutfit
  id: SeniorPhysicianChameleonOutfit
  job: SeniorPhysician
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
