name: CRLF Check

on:
  pull_request_target:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: CRLF Check
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Check for CRLF
      run: Tools/check_crlf.py
