# SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
# SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    name: Submodule update in pr found
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Maintenance') }}
    steps:
      - name: Fail
        run: exit 1
