# SPDX-FileCopyrightText: 2025 Sector-Vestige contributors
# SPDX-FileCopyrightText: 2021 Paul <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2022 0x6273 <0x40@keemail.me>
# SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2022 Vera Aguilera Puerto <gradientvera@outlook.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 BuildTools <unconfigured@null.spigotmc.org>
# SPDX-FileCopyrightText: 2024 Jezithyr <jezithyr@gmail.com>
# SPDX-FileCopyrightText: 2024 Kelderan <66748890+KeldWolf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Matt <psykzz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nikolai Korolev <korolevns98@gmail.com>
# SPDX-FileCopyrightText: 2025 Myra <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 10 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fail if we are attempting to run on the master branch
      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'space-wizards/space-station-14'}}
      run: exit 1

    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1
    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform win-arm64 --platform linux-x64 --platform linux-arm64 --platform osx-x64 --platform osx-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Upload build artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: release/*.zip
        compression-level: 0
        retention-days: 0

    - name: Publish version
      run: Tools/publish_multi_request.py
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

#    - name: Publish changelog (Discord)
#      run: Tools/actions_changelogs_since_last_run.py
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

#    - name: Publish changelog (RSS)
#      run: Tools/actions_changelog_rss.py
#      env:
#        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}

    - uses: geekyeggo/delete-artifact@v5
      if: always()
      with:
        name: build
