name: RSI Validator

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request_target:
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          submodules: 'true'
      - name: Setup Submodule
        run: git submodule update --init
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
